### ISSUE TITLE
disable closed loop fueling if there was recent fuel cut

### ISSUE THREAD

**Issue by mck1117** [FOME-Tech/fome-fw#36]
Looks like this is done for DFCO, but not for other fuel cut reasons (rev limit etc)

**Comment by alrijleh** [comment]
Closed loop fuel corrections already appear to pause after any fuel cut.  Is the enhancement to use a configurable delay for any fuel cut, rather than it being hard coded as it is now?

https://github.com/FOME-Tech/fome-fw/blob/2bf0fa43d13e3c43a859189bc4aa47833d1ba4db/firmware/controllers/math/closed_loop_fuel.cpp#L90-L103

**Comment by mck1117** [comment]
Looks like this was done already in a861d76da613f0337f54400d8f5cb4e61ad15406
